export const projects = [
    {
      name: "Hutly Estate",
      description: "Description 1",
      about: ["About 1", "Industy", "Company size"],
      gallery: ["/hutly/01_menu.png", "/hutly/02_tastimonials.png", "/hutly/03_services.png","/hutly/04_footer.png", "/hutly/05_projects.png", "/hutly/06_projectview.png","/hutly/07_nextproject.png", "/hutly/08_servicespage.png", "/hutly/09_servicespagelists.png","/hutly/10_serviceview.png", "/hutly/11_nextservice.png", "/hutly/12_contactdirect.png", "/hutly/13_contactform.png", ],
      challenges: ["Challenge 1", "Challenge 2", "Challenge 3"],
      solutions: ["Solutions 1", "Solutions 2", "Solutions 3"],
      result: "Result",
      feedback: "Feedback",
      credits: "//",
      services: ["Brand Design", "Web Design", "Web Development", "Interaction Design", "SEO"],
      location: "Belgrade, Serbia",
      year: "2024",
      thumb: "euroexotics.png",
      url: "hutlyestate",
      classLists:
        "bg-yellow-500 opacity-100 rounded-[5%] shadow-[0_3px_10px_rgba(0,0,0,0.2)] shadow-yellow-500",
      
    },

    {
      name: "Hutly Estate",
      description: "Description 1",
      about: ["About 1", "Industy", "Company size"],
      gallery: ["solveitx.png", "solveitx.png", "solveitx.png"],
      challenges: ["Challenge 1", "Challenge 2", "Challenge 3"],
      solutions: ["Solutions 1", "Solutions 2", "Solutions 3"],
      result: "Result",
      feedback: "Feedback",
      credits: "Credits",
      services: ["Service 1", "Service 2", "Service 3"],
      location: "Location",
      year: "Year",
      thumb: "euroexotics.png",
      url: "hutlyestate",
      classLists:
        "bg-yellow-500 opacity-100 rounded-[5%] shadow-[0_3px_10px_rgba(0,0,0,0.2)] shadow-yellow-500",
    },
    {
      name: "Hutly Estate",
      description: "Description 1",
      about: ["About 1", "Industy", "Company size"],
      gallery: ["solveitx.png", "solveitx.png", "solveitx.png"],
      challenges: ["Challenge 1", "Challenge 2", "Challenge 3"],
      solutions: ["Solutions 1", "Solutions 2", "Solutions 3"],
      result: "Result",
      feedback: "Feedback",
      credits: "Credits",
      services: ["Service 1", "Service 2", "Service 3"],
      location: "Location",
      year: "Year",
      thumb: "euroexotics.png",
      url: "hutlyestate",
      classLists:
        "bg-yellow-500 opacity-100 rounded-[5%] shadow-[0_3px_10px_rgba(0,0,0,0.2)] shadow-yellow-500",
    },
    {
      name: "Hutly Estate",
      description: "Description 1",
      about: ["About 1", "Industy", "Company size"],
      gallery: ["solveitx.png", "solveitx.png", "solveitx.png"],
      challenges: ["Challenge 1", "Challenge 2", "Challenge 3"],
      solutions: ["Solutions 1", "Solutions 2", "Solutions 3"],
      result: "Result",
      feedback: "Feedback",
      credits: "Credits",
      services: ["Service 1", "Service 2", "Service 3"],
      location: "Location",
      year: "Year",
      thumb: "euroexotics.png",
      url: "hutlyestate",
      classLists:
        "bg-yellow-500 opacity-100 rounded-[5%] shadow-[0_3px_10px_rgba(0,0,0,0.2)] shadow-yellow-500",
    },
  ];
  