export const projects = [
    {
      name: "Hutly Estate",
      description: "Hutly Estate is a web development project I completed for a real estate agency based in Belgrade, Serbia. The project involved designing and developing a modern responsive website that showcases their properties, services and contact information. The website is built using React, NextJS and Tailwind CSS. The project required me to work closely with the client to understand their needs and develop a solution that meets their expectations.",
      about: [
        "Hutly Estate is a web development project I completed for a real estate agency based in Belgrade, Serbia. The agency specializes in providing exceptional property management services, helping numerous clients to buy, sell and rent properties in Belgrade and its surrounding areas.",
        "The real estate industry is a dynamic and competitive market, with many players offering similar services. However, Hutly Estate stands out due to its strong online presence, professional staff and commitment to providing excellent customer service.",
        "The agency operates in a rapidly evolving market where technology plays a crucial role in the way businesses operate. As such, Hutly Estate recognises the importance of having a website that is user-friendly, visually appealing, and easy to navigate. The website is also designed to be responsive, allowing users to access the agency's services from any device.",
      ],
      gallery: ["/hutly/01_menu.png", "/hutly/02_tastimonials.png", "/hutly/03_services.png","/hutly/04_footer.png", "/hutly/05_projects.png", "/hutly/06_projectview.png","/hutly/07_nextproject.png", "/hutly/08_servicespage.png", "/hutly/09_servicespagelists.png","/hutly/10_serviceview.png", "/hutly/11_nextservice.png", "/hutly/12_contactdirect.png", "/hutly/13_contactform.png", ],
      challenges: ["Challenge 1", "Challenge 2", "Challenge 3"],
      solutions: ["Solutions 1", "Solutions 2", "Solutions 3"],
      result: "Result",
      feedback: "Feedback",
      credits: "//",
      services: ["Brand Design", "Web Design", "Web Development", "Interaction Design", "SEO"],
      location: "Belgrade, Serbia",
      year: "2024",
      thumb: "/hutlymain.png",
      url: "hutlyestate",
      classLists:
        "bg-yellow-500 opacity-100 rounded-[5%] shadow-[0_3px_10px_rgba(0,0,0,0.2)] shadow-yellow-500",
      
    },

    {
      name: "Edge Store",
      description: "Edge Store is a web development project I completed for an electrical company based in Germany. The company offers a wide range of electrical services, including electrical installations, repairs and maintenance, as well as selling electrical materials and equipment. The website is designed to be user-friendly, visually appealing, and easy to navigate, allowing users to access the company's services and contact information from any device.",
      about: [
        "Edge Store is an electrical company based in Germany. The company offers a wide range of electrical services, including electrical installations, repair and maintenance, as well as selling electrical materials and equipment. The company has a strong reputation for providing high-quality services, excellent customer service and competitive pricing.",
        "The company operates in a rapidly evolving market where technology plays a crucial role in the way businesses operate. As such, the company recognises the importance of having a website that is user-friendly, visually appealing, and easy to navigate. The website is also designed to be responsive, allowing users to access the company's services and contact information from any device.",
        "The company is located in Germany and has a team of experienced and skilled electricians who provide a wide range of electrical services. The company prides itself on its excellent customer service, competitive pricing and commitment to providing high-quality services.",
      ],
      gallery: ["solveitx.png", "solveitx.png", "solveitx.png"],
      challenges: [
        "Challenge 1: Create a responsive website with a dark mode and a hamburger menu",
        "Challenge 2: Implement a custom scroll animation when scrolling to the footer",
        "Challenge 3: Use CSS variables to style the website",
      ],
      solutions: [
        "Solve a responsive website with a dark mode and a hamburger menu",
        "Implement a custom scroll animation when scrolling to the footer",
        "Use CSS variables to style the website",
      ],
      result: "Result: A modern responsive website with a dark mode and a hamburger menu, a custom scroll animation when scrolling to the footer, and CSS variables to style the website.",
      feedback: `"I am extremely happy with the website that I created for my company, Edge Store. The website is modern, responsive, and easy to navigate. I received numerous positive comments from my clients about the website and how it makes it easy for them to find the information they need. The website also looks great on all devices, which is important for me since most of my clients are busy professionals who are always on-the-go. I would highly recommend myself to anyone looking for a professional web development service." - Darijo Grabovac, Owner of Edge Store`,
      credits: "Logo Design: Zoran Lazic",
      services: ["Web Development", "Web Design", "Interaction Design", "SEO"],
      location: "Germany",
      year: "2024",
      thumb: "/edgestore.png",
      url: "edgestore",
      classLists:
        "bg-yellow-500 opacity-100 rounded-[5%] shadow-[0_3px_10px_rgba(0,0,0,0.2)] shadow-yellow-500",
    },
    {
      name: "Hutly Estate",
      description: "Description 1",
      about: ["About 1", "Industy", "Company size"],
      gallery: ["solveitx.png", "solveitx.png", "solveitx.png"],
      challenges: ["Challenge 1", "Challenge 2", "Challenge 3"],
      solutions: ["Solutions 1", "Solutions 2", "Solutions 3"],
      result: "Result",
      feedback: "Feedback",
      credits: "Credits",
      services: ["Service 1", "Service 2", "Service 3"],
      location: "Location",
      year: "Year",
      thumb: "euroexotics.png",
      url: "hutlyestate",
      classLists:
        "bg-yellow-500 opacity-100 rounded-[5%] shadow-[0_3px_10px_rgba(0,0,0,0.2)] shadow-yellow-500",
    },
    {
      name: "Hutly Estate",
      description: "Description 1",
      about: ["About 1", "Industy", "Company size"],
      gallery: ["solveitx.png", "solveitx.png", "solveitx.png"],
      challenges: ["Challenge 1", "Challenge 2", "Challenge 3"],
      solutions: ["Solutions 1", "Solutions 2", "Solutions 3"],
      result: "Result",
      feedback: "Feedback",
      credits: "Credits",
      services: ["Service 1", "Service 2", "Service 3"],
      location: "Location",
      year: "Year",
      thumb: "euroexotics.png",
      url: "hutlyestate",
      classLists:
        "bg-yellow-500 opacity-100 rounded-[5%] shadow-[0_3px_10px_rgba(0,0,0,0.2)] shadow-yellow-500",
    },
  ];
  