export const projects = [
  {
    name: "Luxury Car Event",
    description: "Luxury Sport Car Event je ekskluzivni događaj koji privlači preduzetnike i istinske zaljubljenike u sportske i luksuzne automobile. Ova jedinstvena manifestacija koja se prvi put organizuje u Banjaluci predstavlja kombinaciju vrhunskog adrenalina, umrežavanja i nezaboravnog luksuza. Vlasnike automobila želimo da ugostimo na najljepši mogući način u našem gradu. ",
    about: [
      "Svrha je visokokvalitetno druženje, spajanje novih poznanstva, upoznavanje i razgledanje grada Banja Luka, spoj spektakularnih automobila i glamuroznog događaja, kao i mogućnost posjetnicima da dožive manifestaciju toga tipa u Banjaluci.",
      "Event je privatnog tipa za vlasnike egzotičnih automobila, tako je i učešće ograničeno i samo na poziv moguće. Naš dugoročni plan je da se ova manifestacija održava svake godine.",
    ],
    gallery: ["mobile1.png", "mobile2.png", "02desktop.png"],
    challenges: ["Challenge 1", "Challenge 2", "Challenge 3"],
    solutions: ["Solutions 1", "Solutions 2", "Solutions 3"],
    result: "Result",
    feedback: "Feedback",
    credits: "//",
    services: [ "Web Design", "Web Development", "Interaction Design", "SEO"],
    location: "Banja Luka, Bosnia and Herzegovina",
    year: "2024",
    thumb: "/luxurycarevent.mp4",
    url: "luxurycarevent",
    link: "https://luxurycarevent.vercel.app/",
    classLists:
      "#455CE9",
    hasAdmin: false,
    screen: "none",
    hasVideo: false,
    hasGallery: false,
  },
    {
      name: "Hutly Estate",
      description: "Hutly Estate is a web development project I completed for a real estate agency based in Belgrade, Serbia. The project involved designing and developing a modern responsive website that showcases their properties, services and contact information. The website is built using React, NextJS and Tailwind CSS. The project required me to work closely with the client to understand their needs and develop a solution that meets their expectations.",
      about: [
        "Hutly Estate is a web development project I completed for a real estate agency based in Belgrade, Serbia. The agency specializes in providing exceptional property management services, helping numerous clients to buy, sell and rent properties in Belgrade and its surrounding areas.",
        "The real estate industry is a dynamic and competitive market, with many players offering similar services. However, Hutly Estate stands out due to its strong online presence, professional staff and commitment to providing excellent customer service.",
        "The agency operates in a rapidly evolving market where technology plays a crucial role in the way businesses operate. As such, Hutly Estate recognises the importance of having a website that is user-friendly, visually appealing, and easy to navigate. The website is also designed to be responsive, allowing users to access the agency's services from any device.",
      ],
      gallery: ["00mobile.png", "01mobile.png", "02desktop.png"],
      challenges: ["Challenge 1", "Challenge 2", "Challenge 3"],
      solutions: ["Solutions 1", "Solutions 2", "Solutions 3"],
      result: "Result",
      feedback: "Feedback",
      credits: "//",
      services: ["Brand Design", "Web Design", "Web Development", "Interaction Design", "SEO"],
      location: "Belgrade, Serbia",
      year: "2024",
      thumb: "/hutly.mp4",
      url: "hutly",
      link: "https://estate-hutly.vercel.app/",
      classLists:
        "#455CE9",
      hasAdmin: false,
      screen: "laptop",
      hasVideo: true,
      hasGallery: true,
    },

    {
      name: "Edge Store",
      description: "Edge Store is a web development project I completed for an electrical company based in Germany. The company offers a wide range of electrical services, including electrical installations, repairs and maintenance, as well as selling electrical materials and equipment. The website is designed to be user-friendly, visually appealing, and easy to navigate, allowing users to access the company's services and contact information from any device.",
      about: [
        "Edge Store is an electrical company based in Germany. The company offers a wide range of electrical services, including electrical installations, repair and maintenance, as well as selling electrical materials and equipment. The company has a strong reputation for providing high-quality services, excellent customer service and competitive pricing.",
        "The company operates in a rapidly evolving market where technology plays a crucial role in the way businesses operate. As such, the company recognises the importance of having a website that is user-friendly, visually appealing, and easy to navigate. The website is also designed to be responsive, allowing users to access the company's services and contact information from any device.",
        "The company is located in Germany and has a team of experienced and skilled electricians who provide a wide range of electrical services. The company prides itself on its excellent customer service, competitive pricing and commitment to providing high-quality services.",
      ],
      gallery: ["mobile1.png", "mobile2.png", "mobile3.png", "mobile4.png", "mobile5.png", "mobile6.png"],
      challenges: [
        "Challenge 1: Create a responsive website with a dark mode and a hamburger menu",
        "Challenge 2: Implement a custom scroll animation when scrolling to the footer",
        "Challenge 3: Use CSS variables to style the website",
      ],
      solutions: [
        "Solve a responsive website with a dark mode and a hamburger menu",
        "Implement a custom scroll animation when scrolling to the footer",
        "Use CSS variables to style the website",
      ],
      result: "Result: A modern responsive website with a dark mode and a hamburger menu, a custom scroll animation when scrolling to the footer, and CSS variables to style the website.",
      feedback: `"I am extremely happy with the website that I created for my company, Edge Store. The website is modern, responsive, and easy to navigate. I received numerous positive comments from my clients about the website and how it makes it easy for them to find the information they need. The website also looks great on all devices, which is important for me since most of my clients are busy professionals who are always on-the-go. I would highly recommend myself to anyone looking for a professional web development service." - Darijo Grabovac, Owner of Edge Store`,
      credits: "Logo Design: Zoran Lazic",
      services: ["Web Development", "Web Design", "Interaction Design", "SEO"],
      location: "Germany",
      year: "2024",
      thumb: "/edgegroup.mp4",
      url: "edgestore",
      link: "https://www.edge-info.com/",
      classLists:
        "#455CE9",
    },
    {
      name: "Solve ITX",
      description: "Solve ITX is a company that offers a wide range of web services, including web development, digital marketing and more. The company is dedicated to providing exceptional services to its clients and helping them achieve their online goals. With a team of experienced and skilled professionals, Solve ITX is the perfect partner for any business looking to take its online presence to the next level.",
      about: [
        "Solve ITX is a company that offers a wide range of web services, including web development, digital marketing and more.",
        "IT industry",
        "Small team of experienced and skilled professionals."
      ],
      gallery: ["mobile1.png", "mobile2.png", "solveitx.png"],
      challenges: ["Challenge 1", "Challenge 2", "Challenge 3"],
      solutions: ["Solutions 1", "Solutions 2", "Solutions 3"],
      result: "Result",
      feedback: "Feedback",
      credits: "//",
      services: ["Web Design", "Interaction", "Web Development", "SEO"],
      location: "Banja Luka, Bosnia and Herzegovina",
      year: "2023",
      thumb: "/solveitx.mp4",
      url: "solveitx",
      link: "https://solveitx.io/",
      classLists:
        "#455CE9",
    },
    {
      name: "Euro Exotics",
      description: "Euro Exotics is a luxury car rental company based in Europe that offers a unique experience of renting exotic and high-end cars. The company is dedicated to providing an exceptional service to its customers, ensuring that they have an unforgettable experience when renting one of their vehicles. With a wide range of cars available, from supercars to luxury sedans, Euro Exotics is the perfect choice for anyone looking to indulge in a luxurious lifestyle.",
      about: [
        "Euro Exotics is a luxury car rental company based in Europe that offers a unique experience of renting exotic and high-end cars. The company is dedicated to providing an exceptional service to its customers, ensuring that they have an unforgettable experience when renting one of their vehicles. With a wide range of cars available, from supercars to luxury sedans, Euro Exotics is the perfect choice for anyone looking to indulge in a luxurious lifestyle.",
      ],
      gallery: ["mobile1.png", "mobile2.png", "solveitx.png"],
      challenges: ["Challenge 1", "Challenge 2", "Challenge 3"],
      solutions: ["Solutions 1", "Solutions 2", "Solutions 3"],
      result: "Result",
      feedback: "Feedback",
      credits: "Credits",
      services: ["Web Design", "Web Development", "Interaction Design", "SEO", "Brand Design"],
      location: "Europe",
      year: "2024",
      thumb: "/euroexotics.mp4",
      url: "euroexotics",
      link: "https://www.euro-exotics.com/",
      classLists:
        "#455CE9",
    },
    {
      name: "Lugar Estate",
      description: "Lugar Estate is a comprehensive real estate platform tailored to streamline property management for a real estate firm based in Banja Luka, Bosnia and Herzegovina. The project focused on creating a robust, user-friendly website to facilitate property listings, client interactions, and service management. Built with Next.js and Tailwind CSS, the platform ensures responsive design and seamless user experience across devices.",
      about: [
        "Lugar Estate is a real estate platform developed for a firm in Banja Luka, Bosnia and Herzegovina. The project involved creating an intuitive interface for managing property listings, client interactions, and service offerings.",
        "The real estate firm specializes in high-end properties and needed a website that reflects their premium service standards. The platform's design emphasizes simplicity, elegance, and functionality.",
        "Key features include a comprehensive property management system, integrated contact forms, and a responsive design to ensure optimal user experience on all devices."
      ],
      gallery: ["mobile1.png", "mobile2.png", "lugar1.png"],
      challenges: [
        "Challenge 1: Integrate a dynamic property listing system with advanced search functionality.",
        "Challenge 2: Ensure seamless navigation and user experience across all devices.",
        "Challenge 3: Implement robust security measures to protect client data."
      ],
      solutions: [
        "Solution 1: Developed a custom property listing module with advanced search and filtering options.",
        "Solution 2: Utilized responsive design techniques to optimize user experience on mobile and desktop.",
        "Solution 3: Implemented SSL encryption and secure user authentication processes."
      ],
      result: "Result: A modern, responsive real estate platform that enhances client interactions and streamlines property management.",
      feedback: "The feedback from the client was overwhelmingly positive, highlighting the website's ease of use and professional appearance.",
      credits: "",
      services: ["Web Design", "Web Development", "Interaction Design", "SEO"],
      location: "Banja Luka, Bosnia and Herzegovina",
      year: "2023",
      thumb: "/lugar.mp4",
      url: "lugar",
      link: "https://next-real-estate-gilt.vercel.app/",
      classLists: "#455CE9",
    },
    {
      name: "Landwind Template",
      description: "Landwind is a versatile website template designed to cater to various industries, from real estate to corporate businesses. This template offers a clean, modern design with multiple layout options, making it easy to customize for different needs. Built with Next.js and Tailwind CSS, Landwind provides a robust foundation for building responsive, high-performance websites.",
      about: [
        "Landwind is a multipurpose website template created for versatility and ease of customization. Suitable for a range of industries, it provides a solid starting point for building professional websites.",
        "The template features multiple layout options, including homepages, service pages, and contact forms, ensuring it can be tailored to specific business needs.",
        "Landwind is built with a focus on performance and usability, ensuring fast load times and a seamless user experience across all devices."
      ],
      gallery: ["mobile1.png", "mobile2.png", "landwind1.png"],
      challenges: [
        "Challenge 1: Develop a flexible template that can be easily customized for different industries.",
        "Challenge 2: Ensure optimal performance and fast load times.",
        "Challenge 3: Create a modern, clean design that appeals to a wide audience."
      ],
      solutions: [
        "Solution 1: Designed multiple layout options and modular components for easy customization.",
        "Solution 2: Optimized code and assets to ensure fast load times and high performance.",
        "Solution 3: Implemented a clean, modern design aesthetic with intuitive navigation."
      ],
      result: "Result: A versatile, high-performance template that can be customized for various business needs, providing a strong foundation for professional websites.",
      feedback: "Clients praised the template's flexibility and the ease with which they could customize it for their specific needs.",
      credits: "",
      services: ["Web Design", "Web Development", "Template Customization"],
      location: "Banja Luka, Bosnia and Herzegovina",
      year: "2023",
      thumb: "/landwind.mp4",
      url: "landwind",
      link: "https://landwind-beta.vercel.app/",
      classLists: "#455CE9",
    },
    {
      name: "XOXO Bar",
      description: "XOXO.",
      about: [
        
      ],
      gallery: ["mobile1.png", "mobile2.png", "landwind1.png"],
      challenges: [
       
      ],
      solutions: [
        
      ],
      result: "Result: A versatile, high-performance template that can be customized for various business needs, providing a strong foundation for professional websites.",
      feedback: "Clients praised the template's flexibility and the ease with which they could customize it for their specific needs.",
      credits: "",
      services: ["Web Design", "Web Development", "Template Customization"],
      location: "Banja Luka, Bosnia and Herzegovina",
      year: "2023",
      thumb: "/landwind.mp4",
      url: "xoxobar",
      link: "https://xoxobar.vercel.app/",
      classLists: "#455CE9",
    },
    {
      name: "Maximon Real Estate",
      description: "Maximon Real Estate je moderna agencija za nekretnine koja pruža profesionalne usluge kupovine, prodaje i iznajmljivanja nekretnina. Website je dizajniran da pruži jednostavno i efikasno iskustvo za klijente koji traže savršenu nekretninu. Moderan dizajn, responzivna struktura i intuitivna navigacija čine ovaj projekat idealnim za prezentaciju premium nekretnina.",
      about: [
        "Maximon Real Estate je agencija za nekretnine koja se fokusira na pružanje visokokvalitetnih usluga u oblasti nekretnina. Website omogućava klijentima da lako pregledaju dostupne nekretnine, kontaktiraju agente i pronađu savršenu nekretninu za svoje potrebe.",
        "Projekat je razvijen sa fokusom na korisničko iskustvo, brzinu učitavanja i moderni dizajn koji odražava profesionalizam agencije.",
        "Website uključuje napredne filtere za pretragu, galeriju slika, detaljne opise nekretnina i jednostavan sistem za kontakt sa agentima."
      ],
      gallery: ["mobile1.png", "mobile2.png", "mobile1.png"],
      challenges: ["Challenge 1", "Challenge 2", "Challenge 3"],
      solutions: ["Solutions 1", "Solutions 2", "Solutions 3"],
      result: "Result",
      feedback: "Feedback",
      credits: "//",
      services: ["Web Design", "Web Development", "Interaction Design", "SEO"],
      location: "Serbia",
      year: "2025",
      thumb: "/solveitx.mp4",
      url: "maximonrealestate",
      link: "https://maximonrealestate.com/",
      classLists: "#455CE9",
      hasAdmin: false,
      screen: "none",
      hasVideo: false,
      hasGallery: false,
    },
    {
      name: "Mont-AT",
      description: "Mont-AT je profesionalna kompanija koja se bavi montažom i instalacijama različitih sistema. Website je kreiran da prezentuje usluge kompanije na jasan i profesionalan način, omogućavajući klijentima da lako saznaju više o ponuđenim uslugama i kontaktiraju tim za dodatne informacije.",
      about: [
        "Mont-AT je kompanija koja pruža usluge montaže i instalacije različitih sistema. Website je dizajniran da efikasno prezentuje usluge kompanije i omogući klijentima jednostavan način komunikacije.",
        "Projekat je razvijen sa fokusom na profesionalnu prezentaciju usluga, jednostavnu navigaciju i responzivan dizajn koji funkcioniše na svim uređajima.",
        "Website uključuje detaljne opise usluga, galeriju projekata, kontakt formu i informacije o kompaniji."
      ],
      gallery: ["mobile1.png", "mobile2.png", "mobile1.png"],
      challenges: ["Challenge 1", "Challenge 2", "Challenge 3"],
      solutions: ["Solutions 1", "Solutions 2", "Solutions 3"],
      result: "Result",
      feedback: "Feedback",
      credits: "//",
      services: ["Web Design", "Web Development", "Interaction Design", "SEO"],
      location: "Serbia",
      year: "2025",
      thumb: "/solveitx.mp4",
      url: "montat",
      link: "https://mont-at.com/",
      classLists: "#455CE9",
      hasAdmin: false,
      screen: "none",
      hasVideo: false,
      hasGallery: false,
    },
    {
      name: "Lawyer Website Template",
      description: "Lawyer Website Template je profesionalni website template dizajniran specijalno za advokatske kancelarije i pravne usluge. Template nudi moderan, čist dizajn koji odražava profesionalizam i pouzdanost, sa fokusom na prezentaciju usluga, tima i kontakt informacija. Idealno rešenje za advokatske kancelarije koje žele brzo i efikasno da se predstave online.",
      about: [
        "Lawyer Website Template je kompletan template sistem kreiran za advokatske kancelarije. Template uključuje sve potrebne sekcije za profesionalnu prezentaciju pravne prakse.",
        "Dizajn je optimizovan za brzo učitavanje, SEO performanse i jednostavnu navigaciju koja omogućava posetioce da brzo pronađu informacije koje traže.",
        "Template je potpuno responzivan i prilagođen za sve uređaje, sa modernim UI/UX elementima koji pružaju profesionalno iskustvo."
      ],
      gallery: ["mobile1.png", "mobile2.png", "mobile1.png"],
      challenges: ["Challenge 1", "Challenge 2", "Challenge 3"],
      solutions: ["Solutions 1", "Solutions 2", "Solutions 3"],
      result: "Result",
      feedback: "Feedback",
      credits: "//",
      services: ["Web Design", "Web Development", "Template Design", "UI/UX"],
      location: "Serbia",
      year: "2025",
      thumb: "/solveitx.mp4",
      url: "lawyertemplate",
      link: "https://lawyer-v1.vercel.app/",
      classLists: "#455CE9",
      hasAdmin: false,
      screen: "none",
      hasVideo: false,
      hasGallery: false,
    },
    {
      name: "PeakitX",
      description: "PeakitX je digitalna agencija koja pruža kompleksne usluge u oblasti web developmenta, digitalnog marketinga i brandinga. Website je dizajniran da prezentuje kreativnost i profesionalizam agencije, sa fokusom na portfolio projekata i usluge koje nude. Moderan dizajn i inovativni pristup čine ovaj projekat jedinstvenim.",
      about: [
        "PeakitX je digitalna agencija koja kombinuje kreativnost sa tehnološkim ekspertizom. Website je kreiran da efikasno prezentuje usluge agencije i portfolio projekata.",
        "Projekat je razvijen sa fokusom na moderni dizajn, brzinu učitavanja i intuitivnu navigaciju koja omogućava posetiocima da lako saznaju više o uslugama.",
        "Website uključuje portfolio sekciju, detaljne opise usluga, kontakt formu i blog sekciju za deljenje vrednih informacija."
      ],
      gallery: ["mobile1.png", "mobile2.png", "mobile1.png"],
      challenges: ["Challenge 1", "Challenge 2", "Challenge 3"],
      solutions: ["Solutions 1", "Solutions 2", "Solutions 3"],
      result: "Result",
      feedback: "Feedback",
      credits: "//",
      services: ["Web Design", "Web Development", "Brand Design", "Digital Marketing"],
      location: "Switzerland",
      year: "2025",
      thumb: "/solveitx.mp4",
      url: "peakitx",
      link: "https://www.peakitx.ch/",
      classLists: "#455CE9",
      hasAdmin: false,
      screen: "none",
      hasVideo: false,
      hasGallery: false,
    },
    {
      name: "Panic Digital",
      description: "Panic Digital je kreativna digitalna agencija koja se fokusira na kreiranje jedinstvenih digitalnih iskustava. Website kombinuje moderni dizajn sa inovativnim pristupom, prezentujući portfolio projekata i usluge na način koji privlači pažnju. Agencija se ističe kreativnim rešenjima i pažljivim pristupom svakom projektu.",
      about: [
        "Panic Digital je agencija koja se fokusira na kreiranje jedinstvenih digitalnih rešenja za klijente. Website je dizajniran da odražava kreativnost i profesionalizam agencije.",
        "Projekat uključuje moderan dizajn sa fokusom na korisničko iskustvo, brzinu učitavanja i responzivnu strukturu koja funkcioniše na svim uređajima.",
        "Website prezentuje portfolio projekata, detaljne opise usluga, tim agencije i jednostavan način za kontakt sa klijentima."
      ],
      gallery: ["mobile1.png", "mobile2.png", "mobile1.png"],
      challenges: ["Challenge 1", "Challenge 2", "Challenge 3"],
      solutions: ["Solutions 1", "Solutions 2", "Solutions 3"],
      result: "Result",
      feedback: "Feedback",
      credits: "//",
      services: ["Web Design", "Web Development", "Brand Design", "Creative Direction"],
      location: "Serbia",
      year: "2025",
      thumb: "/solveitx.mp4",
      url: "panicdigital",
      link: "https://www.panicdigital.com/",
      classLists: "#455CE9",
      hasAdmin: false,
      screen: "none",
      hasVideo: false,
      hasGallery: false,
    },
    {
      name: "Vunape Restoran",
      description: "Vunape Restoran je moderni website za restoran koji pruža posetiocima jednostavan način da saznaju više o meniju, rezervišu sto i kontaktiraju restoran. Dizajn je kreiran da odražava atmosferu i kvalitet restorana, sa fokusom na prezentaciju hrane i usluga. Responzivna struktura omogućava posetiocima da pristupe informacijama sa bilo kog uređaja.",
      about: [
        "Vunape Restoran je website kreiran za prezentaciju restorana i njegovih usluga. Projekat je dizajniran da pruži jednostavno i prijatno iskustvo za posetioce.",
        "Website uključuje detaljnu prezentaciju menija, galeriju slika hrane, sistem za rezervacije i kontakt informacije. Dizajn je optimizovan da odražava kvalitet i atmosferu restorana.",
        "Projekat je potpuno responzivan i prilagođen za sve uređaje, sa fokusom na brzinu učitavanja i jednostavnu navigaciju."
      ],
      gallery: ["mobile1.png", "mobile2.png", "mobile1.png"],
      challenges: ["Challenge 1", "Challenge 2", "Challenge 3"],
      solutions: ["Solutions 1", "Solutions 2", "Solutions 3"],
      result: "Result",
      feedback: "Feedback",
      credits: "//",
      services: ["Web Design", "Web Development", "UI/UX Design", "SEO"],
      location: "Serbia",
      year: "2026",
      thumb: "/solveitx.mp4",
      url: "vunaperestoran",
      link: "https://vunape-restoran.vercel.app/",
      classLists: "#455CE9",
      hasAdmin: false,
      screen: "none",
      hasVideo: false,
      hasGallery: false,
    },
    {
      name: "Nada Torte",
      description: "Nada Torte je website za poslasticarnicu koja se specijalizuje za kreiranje ukusnih torti i slatkiša. Website je dizajniran da prezentuje proizvode na privlačan način, omogućavajući klijentima da pregledaju ponudu, kontaktiraju poslasticarnicu i naruče proizvode. Dizajn je kreiran da odražava slatkošću i kvalitet proizvoda.",
      about: [
        "Nada Torte je website kreiran za poslasticarnicu koja se fokusira na kreiranje visokokvalitetnih torti i slatkiša. Projekat je dizajniran da privuče pažnju i prezentuje proizvode na najbolji način.",
        "Website uključuje galeriju proizvoda, detaljne opise torti, kontakt formu i informacije o poslasticarnici. Dizajn je optimizovan da odražava slatkošću i kvalitet proizvoda.",
        "Projekat je potpuno responzivan i prilagođen za sve uređaje, sa fokusom na vizuelnu prezentaciju proizvoda i jednostavnu navigaciju."
      ],
      gallery: ["mobile1.png", "mobile2.png", "mobile1.png"],
      challenges: ["Challenge 1", "Challenge 2", "Challenge 3"],
      solutions: ["Solutions 1", "Solutions 2", "Solutions 3"],
      result: "Result",
      feedback: "Feedback",
      credits: "//",
      services: ["Web Design", "Web Development", "UI/UX Design", "SEO"],
      location: "Serbia",
      year: "2026",
      thumb: "/solveitx.mp4",
      url: "nadatorte",
      link: "https://nada-torte-v1.vercel.app/",
      classLists: "#455CE9",
      hasAdmin: false,
      screen: "none",
      hasVideo: false,
      hasGallery: false,
    },
    {
      name: "Pekara Miki",
      description: "Pekara Miki je website za pekaru koja nudi sveže pekarske proizvode. Website je dizajniran da prezentuje proizvode na privlačan način, omogućavajući klijentima da pregledaju ponudu i kontaktiraju pekaru. Dizajn je kreiran da odražava toplinu i kvalitet domaćih pekarskih proizvoda.",
      about: [
        "Pekara Miki je website kreiran za pekaru koja se fokusira na proizvodnju svežih pekarskih proizvoda. Projekat je dizajniran da privuče pažnju i prezentuje proizvode na najbolji način.",
        "Website uključuje galeriju proizvoda, detaljne opise pekarskih proizvoda, kontakt informacije i lokaciju pekare. Dizajn je optimizovan da odražava toplinu i kvalitet domaćih proizvoda.",
        "Projekat je potpuno responzivan i prilagođen za sve uređaje, sa fokusom na vizuelnu prezentaciju proizvoda i jednostavnu navigaciju."
      ],
      gallery: ["mobile1.png", "mobile2.png", "mobile1.png"],
      challenges: ["Challenge 1", "Challenge 2", "Challenge 3"],
      solutions: ["Solutions 1", "Solutions 2", "Solutions 3"],
      result: "Result",
      feedback: "Feedback",
      credits: "//",
      services: ["Web Design", "Web Development", "UI/UX Design", "SEO"],
      location: "Serbia",
      year: "2026",
      thumb: "/solveitx.mp4",
      url: "pekaramiki",
      link: "https://pekara-miki.vercel.app/",
      classLists: "#455CE9",
      hasAdmin: false,
      screen: "none",
      hasVideo: false,
      hasGallery: false,
    },
    {
      name: "Frizerski Salon Iliev",
      description: "Frizerski Salon Iliev je website za frizerski salon koji pruža posetiocima jednostavan način da saznaju više o uslugama, rezervišu termin i kontaktiraju salon. Dizajn je kreiran da odražava modernost i profesionalizam salona, sa fokusom na prezentaciju usluga i galeriju radova. Responzivna struktura omogućava posetiocima da pristupe informacijama sa bilo kog uređaja.",
      about: [
        "Frizerski Salon Iliev je website kreiran za prezentaciju frizerskog salona i njegovih usluga. Projekat je dizajniran da pruži jednostavno i prijatno iskustvo za posetioce.",
        "Website uključuje detaljnu prezentaciju usluga, galeriju radova, sistem za rezervacije i kontakt informacije. Dizajn je optimizovan da odražava modernost i profesionalizam salona.",
        "Projekat je potpuno responzivan i prilagođen za sve uređaje, sa fokusom na brzinu učitavanja i jednostavnu navigaciju."
      ],
      gallery: ["mobile1.png", "mobile2.png", "mobile1.png"],
      challenges: ["Challenge 1", "Challenge 2", "Challenge 3"],
      solutions: ["Solutions 1", "Solutions 2", "Solutions 3"],
      result: "Result",
      feedback: "Feedback",
      credits: "//",
      services: ["Web Design", "Web Development", "UI/UX Design", "SEO"],
      location: "Serbia",
      year: "2026",
      thumb: "/solveitx.mp4",
      url: "frizerskisaloniliev",
      link: "https://frizerski-salon-website.vercel.app/",
      classLists: "#455CE9",
      hasAdmin: false,
      screen: "none",
      hasVideo: false,
      hasGallery: false,
    },
    {
      name: "Forestry Website",
      description: "Forestry Website je profesionalni website kreiran za prezentaciju usluga u oblasti šumarstva i upravljanja šumskim resursima. Website je dizajniran da pruži detaljne informacije o uslugama, projektima i ekspertizi kompanije. Moderan dizajn i jasan sadržaj čine ovaj projekat idealnim za prezentaciju profesionalnih usluga u oblasti šumarstva.",
      about: [
        "Forestry Website je kreiran za kompaniju koja pruža usluge u oblasti šumarstva i upravljanja šumskim resursima. Projekat je dizajniran da efikasno prezentuje usluge i ekspertizu kompanije.",
        "Website uključuje detaljne opise usluga, galeriju projekata, informacije o kompaniji i kontakt formu. Dizajn je optimizovan da odražava profesionalizam i pouzdanost kompanije.",
        "Projekat je potpuno responzivan i prilagođen za sve uređaje, sa fokusom na jasan sadržaj i jednostavnu navigaciju."
      ],
      gallery: ["mobile1.png", "mobile2.png", "mobile1.png"],
      challenges: ["Challenge 1", "Challenge 2", "Challenge 3"],
      solutions: ["Solutions 1", "Solutions 2", "Solutions 3"],
      result: "Result",
      feedback: "Feedback",
      credits: "//",
      services: ["Web Design", "Web Development", "UI/UX Design", "SEO"],
      location: "Serbia",
      year: "2026",
      thumb: "/solveitx.mp4",
      url: "forestrywebsite",
      link: "https://forestry-website-v1.vercel.app/",
      classLists: "#455CE9",
      hasAdmin: false,
      screen: "none",
      hasVideo: false,
      hasGallery: false,
    },
    {
      name: "Salon Auta",
      description: "Salon Auta je website za rent a car agenciju koja nudi širok spektar vozila za iznajmljivanje. Website je dizajniran da prezentuje vozila na privlačan način, omogućavajući klijentima da pregledaju ponudu, rezervišu vozilo i kontaktiraju agenciju. Dizajn je kreiran da odražava profesionalizam i pouzdanost agencije.",
      about: [
        "Salon Auta je website kreiran za rent a car agenciju koja se fokusira na pružanje visokokvalitetnih usluga iznajmljivanja vozila. Projekat je dizajniran da privuče pažnju i prezentuje vozila na najbolji način.",
        "Website uključuje galeriju vozila, detaljne opise automobila, sistem za rezervacije i kontakt informacije. Dizajn je optimizovan da odražava profesionalizam i pouzdanost agencije.",
        "Projekat je potpuno responzivan i prilagođen za sve uređaje, sa fokusom na vizuelnu prezentaciju vozila i jednostavnu navigaciju."
      ],
      gallery: ["mobile1.png", "mobile2.png", "mobile1.png"],
      challenges: ["Challenge 1", "Challenge 2", "Challenge 3"],
      solutions: ["Solutions 1", "Solutions 2", "Solutions 3"],
      result: "Result",
      feedback: "Feedback",
      credits: "//",
      services: ["Web Design", "Web Development", "UI/UX Design", "SEO"],
      location: "Serbia",
      year: "2026",
      thumb: "/solveitx.mp4",
      url: "salonauta",
      link: "https://salon-auta-v1.vercel.app/",
      classLists: "#455CE9",
      hasAdmin: false,
      screen: "none",
      hasVideo: false,
      hasGallery: false,
    },
    {
      name: "No Panic Analysis",
      description: "No Panic Analysis je AI-powered aplikacija koja pruža naprednu analizu sportskih utakmica i predviđanja. Aplikacija koristi veštačku inteligenciju za analizu statistika, performansi timova i igrača, pružajući korisnicima detaljne uvide i predviđanja. Moderan dizajn i napredna funkcionalnost čine ovu aplikaciju jedinstvenom u svojoj kategoriji.",
      about: [
        "No Panic Analysis je AI-powered aplikacija koja kombinuje veštačku inteligenciju sa sportskom analitikom. Projekat je dizajniran da pruži korisnicima detaljne uvide i predviđanja za sportske utakmice.",
        "Aplikacija koristi napredne algoritme za analizu statistika, performansi timova i igrača, pružajući korisnicima precizne predviđanja i analize. Dizajn je optimizovan za jednostavnu navigaciju i brzo učitavanje podataka.",
        "Projekat je potpuno responzivan i prilagođen za sve uređaje, sa fokusom na korisničko iskustvo i preciznost predviđanja."
      ],
      gallery: ["mobile1.png", "mobile2.png", "mobile1.png"],
      challenges: ["Challenge 1", "Challenge 2", "Challenge 3"],
      solutions: ["Solutions 1", "Solutions 2", "Solutions 3"],
      result: "Result",
      feedback: "Feedback",
      credits: "//",
      services: ["Web Development", "AI Integration", "Data Analysis", "UI/UX Design"],
      location: "Serbia",
      year: "2026",
      thumb: "/solveitx.mp4",
      url: "nopanicanalysis",
      link: "https://sport-predicts.vercel.app/",
      classLists: "#455CE9",
      hasAdmin: false,
      screen: "none",
      hasVideo: false,
      hasGallery: false,
    }
  ];
  